### ISSUE TITLE
Ruby group project : set up Kanban board

### ISSUE THREAD

**Issue by BouaikIlham** [BouaikIlham/Ruby-group-capstone#26]
In this milestone, we are two students: @principles31, and @BouaikIlham we set up the Kanban board where we assigned tasks
and here is the link for our project: 
         - [ ] https://github.com/BouaikIlham/Ruby-group-capstone/projects/1

**Comment by muneebulrehman** [comment]
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳
Congratulations! 🎉 

# Status: Approved✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by principles31** [comment]
@muneebulrehman Thank you for your approval
